language: python
python:
    - "2.7"
install:
    - pip install pytest-cov
    - pip install pytest-pep8
    - pip install coveralls
    - pip install httpretty
script: py.test ./tests/test_api.py --pep8 smsaero -v --cov smsaero --cov-report term-missing
after_success:
    - coveralls
